estimator:

  - name: lineal_regression
    params: {}


      

data:
  filepath: ./dataset/train_regression.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: lineal_regression
      params:
        fit_intercept: [True, False] #Linear Regression
        positive: [True, False] #Linear Regression


export:
  output_dir: models

reports:
  dir: reports
