estimator:

  - name: lineal_regression
    params: {}
<<<<<<< HEAD
=======

stage:
  name: h_0
  
>>>>>>> 6f9fc89ef79b6f99e911d901ddb1577122e0850e
data:
  filepath: ./dataset/train_regression.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: lineal_regression
      params:
        fit_intercept: [True, False] #Linear Regression
        positive: [True, False] #Linear Regression


export:
  output_dir: models

reports:
  dir: reports
